use std::env::VarError;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum Error {
    #[error("failed to parse/write config: {0}")]
    Parse(#[from] serde_yaml::Error),
    #[error("value of {0} has wrong YAML type")]
    ExpectedOtherType(String),
    #[error("name in your config conflicts with generated config: {0}")]
    NameConflict(String),
    #[error("I/O Error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Fmt Error")]
    Fmt(#[from] std::fmt::Error),
    #[error("Please only use utf-8 in your path")]
    NonUTF8Path,
    #[error("Child process \"{0}\" returned failure")]
    ChildProcessFailure(String),
    #[error("Custom executable path is required for client \"{0}\"")]
    MissingExecutable(String),
    #[error("Missing info about the link from {0} to {1}")]
    MissingInfoForDestination(String, String),
    #[error(
        "Network layout is generated by ethshadow, use \
                ethereum.locations and ethereum.reliabilities instead"
    )]
    ExistingNetwork,
    #[error("Unknown location \"{0}\"")]
    UnknownLocation(String),
    #[error("Unknown reliability \"{0}\"")]
    UnknownReliability(String),
    #[error("Unknown client \"{0}\"")]
    UnknownClient(String),
    #[error("You have specified {0} total validators, but VCs have requested {1}")]
    MoreValidatorsRequested(usize, usize),
    #[error(
        "You have configured all validator clients to take a specific number of validators \
            and it disagrees with the configured total number of validators"
    )]
    LeftoverValidators,
    #[error(
        "The specified number of nodes ({0}) must be divisible by the number of possible \
                combinations ({1})"
    )]
    InconsistentCount(usize, usize),
    #[error("Missing env var: {0}")]
    MissingEnvVar(#[from] VarError),
    #[error("Output data folder already exists")]
    OutputFolderExists,
    #[error(
        "You must specify a global validator count and/or a validator count for each \
            validator client"
    )]
    MissingValidatorCount,
    #[error(
        "You must specify a reliability and location, and no network_node_id in your custom hosts"
    )]
    InvalidShadowHost,
}
